databases:
  - name: mysite
    databaseName: mysite_54am
    user: mysite
    password: r8X65gI7USSd4Hi1BU1ZZuG7mDviS8GI
    plan: free
    host: dpg-cutn8rhopnds739otj7g-a
    port: 5432

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://mysite:r8X65gI7USSd4Hi1BU1ZZuG7mDviS8GI@dpg-cutn8rhopnds739otj7g-a:5432/mysite_54am"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: KEY
        value: AIzaSyAsywiNJodkobG2OptKpyer2fz696hNUW0