default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: dpg-cutn8rhopnds739otj7g-a
  port: 5432
  username: mysite
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: mysite_54am

development:
  <<: *default

test:
  <<: *default
  database: mysite_test

production:
  <<: *default